In [17]:
import torch
import torch.nn as nn
import numpy as np
from torch.nn import functional as F
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [18]:
%%time
start_time = time.time()

zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")

 0.00101209
CPU times: total: 0 ns
Wall time: 1.01 ms


In [19]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.31856632
0.41567779


In [20]:
probabilities = torch.tensor([0.1,0.9])

samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([0, 0, 1, 1, 1, 1, 1, 1, 1, 1])


In [21]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [22]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [23]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [24]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [25]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [26]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [27]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3,3, bias = False)
print(linear(sample))

tensor([ 2.9518,  0.2397, 12.3734], grad_fn=<SqueezeBackward4>)


In [29]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [30]:
a = torch.rand(2,3,5)
print(a.shape)
x,y,z = a.shape
a = a.view(x,y,z)
print(x,y,z)
print(a.shape)


torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])


In [16]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)

print(output[:, -1, :])

tensor([[8.7241e-01, 7.2283e-01, 6.2497e-01, 9.0489e-02, 6.3127e-01, 4.9173e-01,
         2.7254e-01, 5.9290e-01, 3.1863e-01, 8.5435e-01],
        [1.6983e-01, 9.4444e-01, 2.9538e-01, 3.3494e-01, 6.5099e-01, 5.6376e-01,
         8.6720e-01, 6.3401e-01, 9.6647e-01, 4.9838e-01],
        [8.0361e-01, 2.2404e-02, 7.1707e-01, 5.9874e-01, 2.8440e-01, 5.6226e-01,
         6.3254e-01, 2.0368e-02, 7.0139e-01, 3.1283e-01],
        [4.4979e-01, 1.9734e-01, 8.3504e-01, 3.9518e-01, 4.7896e-01, 5.3908e-01,
         5.4095e-01, 3.8593e-01, 7.6635e-01, 2.3713e-01],
        [2.5995e-01, 2.3172e-01, 5.9985e-01, 4.3423e-01, 6.9812e-01, 7.5065e-01,
         8.1169e-01, 3.8900e-01, 8.8930e-01, 3.5080e-01],
        [7.4753e-01, 2.3580e-01, 1.3115e-01, 8.7607e-01, 9.9926e-01, 4.5421e-01,
         3.8141e-01, 2.3232e-01, 2.5068e-01, 9.5773e-01],
        [3.3735e-01, 4.2113e-01, 5.5207e-01, 7.8863e-01, 1.7549e-01, 3.1599e-01,
         4.8129e-01, 2.4215e-01, 3.3509e-01, 1.0078e-01],
        [7.6239e-03, 8.7779

IndexError: too many indices for tensor of dimension 2

In [39]:
x =  torch.tensor([-0.05], dtype = torch.float32)
y = F.tanh(x)
print(y)

tensor([-0.0500])
